destination: docs/

# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jae Hyung Ju
title: ECE PhD Candidate at Georgia Tech
email: jhju [at] gatech [dot] edu

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
# github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: jae-hyung-ju
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0009-0007-8401-0773

# Additional icon links
additional_links:
- title: google scholar
  icon: fas fa-globe
  url: https://scholar.google.com/citations?user=0bATY0wAAAAJ
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: About
about_profile_image: images/me.png
about_content: | # this will include new lines to allow paragraphs
  I am a first-year Electrical and Computer Engineering PhD candidate at [Georgia Tech Computer-aided Design Lab (GTCAD)](https://gtcad.gatech.edu/), advised by Professor [Sung-Kyu Lim](https://limsk.ece.gatech.edu/). I am currently interested in computer architecture and the co-design of system and technology.

  I received my BS from Seoul National University, where I was advised by Professor [Jung Ho Ahn](https://scale.snu.ac.kr/members/) on accelerating Fully Homomorphic Encryption, and by Professor [Jinho Lee](https://iamjinholee.github.io/jinho.html) on designing a DRAM function-in-memory for efficient graph processing.

  You can view my CV [here](CV_2408.pdf).
#, my name's Brett and I'm a senior network system administrator. As well as administrating systems I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.
#
#  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

content:
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Super awesome project
  #       link: github.com/sproogen
  #       # link_text: Project Website
  #       additional_links:
  #         - title:  sproogen/modern-resume-theme
  #           icon: fab fa-github
  #           url: github.com/sproogen/modern-resume-theme
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #       description: | # this will include new lines to allow paragraphs
  #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Education
    layout: text
    content: | # this will include new lines to allow paragraphs
      2024--Current **Georgia Institute of Technology**, Atlanta, United States
      - PhD in Electrical and Computer Engineering

      2018--2024 **Seoul National University (SNU)**, Seoul, South Korea
      - BS in Electrical and Computer Engineering

  - title: Work Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: CryptoLab Inc.
        # link_text: boringcompany.com
        sub_title: Research Intern
        caption: Apr 2024 - Jul 2024
        description: | # this will include new lines to allow paragraphs
            - Designed and implemented the initial structure of a new Fully Homomorphic Encryption (FHE) library, with a focus on enabling easy integration of existing/future optimizations. (C++, CUDA)
            - Optimized the latency of Llama2 and ResNet18 within FHE.

  - title: Publications # Title for the section
    layout: text # Type of content section (list/text)
    content: | # this will include new lines to allow paragraphs
      - **Neujeans: Private Neural Network Inference with Joint Optimization of Convolution and FHE Bootstrapping** \\
        \***Jae Hyung Ju**, \*Jaiyoung Park, Jongmin Kim, Minsik Kang, Donghwan Kim, Jung Hee Cheon, and Jung Ho Ahn (\*equal contribution)\\
        ACM Conference on Computer and Communications Security (CCS), 2024

      - **A Case for In-Memory Random Scatter-Gather for Fast Graph Processing** \\
        Changmin Shin, Taehee Kwon, Jaeyong Song, **Jae Hyung Ju**, Frank Liu, Yeonkyu Choi, and Jinho Lee \\
        IEEE Computer Architecture Letters (CAL), 2024

  # - title: Publications
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #   - 
  # 
  # ACM Conference on Computer and Communications Security (CCS), to appear

  #     Look at this cool image  
  #     ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
